### ISSUE TITLE
Backport the SCL enablement and layering framework from RHCSL

### ISSUE THREAD

**Issue by mfojtik** [openshift/sti-base#26]
We should backport the layering scripts and SCL enablement scripts from the RHCSL repositories and make them default for all images we have. This does not affect the functionality but makes the images more flexible when users want to layer or extended the default entrypoint with custom funcionality (like replication, custom bootstraping, etc...)
The RHCSL also provide a way to add custom 'hooks' (shell scripts) which allows extending the default image functionality without overriding the existing entrypoint. 

The repository is here:
https://github.com/sclorg/rhscl2dockerfile/tree/master/common

@bparees I dunno if this is something we want to do for the 3.0 or post-3.0. This might be a lot of work if we will attempt to migrate the master/slave replication stuff we currently ship in scripts for database images (so I would prefer post-3.0).

(sorry for reporting this bug here, but it kind of touch all images... perhaps a [Trello](https://trello.com/c/tPTMBL5K/588-migrate-openshift-images-to-rhcsl-layering) card would be better)

**Comment by mfojtik** [comment]
@jhadvig @soltysh @praiskup @hhorak FYI.

**Comment by soltysh** [comment]
:+1: for trello

**Comment by mfojtik** [comment]
@soltysh trelloed... now where is CLOSE_UPSTREAM button :-)
