### ISSUE TITLE
Add git package

### ISSUE THREAD

**Issue by jhadvig** [openshift/sti-base#28]
It would be good to have this git installed in our base image. I know that Ruby, PhP and also NodeJS can install libs by using git.

**Comment by jhadvig** [comment]
@mfojtik @bparees @mnagy thoughts ?

**Comment by mfojtik** [comment]
+1

**Comment by bparees** [comment]
it's ok with me.  Note that @smarterclayton wanted us to have sti-base be based on origin-base in which case i believe git is already there.  but changing the base image is a post-3.0 thing.  adding git can be done anytime if you want to.

**Comment by smarterclayton** [comment]
Yeah, just open a post 3.0 issue to do the refactor to use origin-base.

**Comment by soltysh** [comment]
+1

**Comment by jhadvig** [comment]
Ok I've added git and created a new 'Post 3.0 refactoring' issue - https://github.com/openshift/sti-base/issues/30
