### ISSUE TITLE
Post 3.0 refactoring

### ISSUE THREAD

**Issue by jhadvig** [openshift/sti-base#30]
Change base image to origin-base + remove dup. packages:
https://github.com/openshift/origin/blob/master/images/base/Dockerfile

**Comment by jhadvig** [comment]
@smarterclayton are we going to have the openshift/origin-base-centos7 ? If yeas whats the eta ?

**Comment by smarterclayton** [comment]
I think we'll keep origin base as is

**Comment by bparees** [comment]
@smarterclayton @jhadvig 
The question was supposed to be about having an origin-base-rhel7.

if we move our sti-base-centos to use origin-base-centos7 instead of using centos7 directly, we also want to move our sti-base-rhel7 to use origin-base-rhel7, but there isn't one.

**Comment by smarterclayton** [comment]
There is now :)

**Comment by smarterclayton** [comment]
Actually, the name is probably wrong - openshift/ose-base is more accurate (whatever prefix we chose)

**Comment by mfojtik** [comment]
@smarterclayton what is the benefit of using openshift/ose-base instead of rhel7 or centos7 directly? Will openshift/ose-base pickup all updated provided by centos:7?

**Comment by bparees** [comment]
@mfojtik the main reasons were:
1) slightly less pulling of images to nodes (more shared layers since things like origin-deployer will share layers with all our STI builder images)
2) slightly less disk space consumed (basically for the same reason as #1... no duplicate content like "git" due to different but really the same layers.

**Comment by mfojtik** [comment]
@bparees 1) the origin-base is based on centos7 afaik, so the layer is already on node and technically there should be nothing to pull... 2) yeah, only git will be duplicated at this moment....

i'm OK with going with origin-base...  we have to make sure that image is squashed.

**Comment by smarterclayton** [comment]
Ultimately we will make this a build problem - just haven't got there yet.

**Comment by jhadvig** [comment]
updated the https://github.com/openshift/sti-base/pull/49 so it now the centos7 based Dockerfile has base image openshift/origin-base and the rhel7 has openshift/ose-base as base image

**Comment by rhcarvalho** [comment]
ping -- is this still supposed to be an open issue?

**Comment by bparees** [comment]
@rhcarvalho yes there's still a desire to make sti-base be built on top of origin-base instead of building on top of centos directly. Not a very high priority desire, but a desire nonetheless.

Shouldn't be assigned to @jhadvig anymore though :)

**Comment by jhadvig** [comment]
... so much memories... :-D

**Comment by smarterclayton** [comment]
After 1.2 all of the images in origin source tree will be reparented under
openshift/origin.  At that point openshift/origin is effectively free -
every node will have it.

**Comment by mfojtik** [comment]
@smarterclayton the openshift/origin has entrypoint set to openshift, so if we are going to use it as base, we will have to change that entrypoint here. On the other hand, I like the idea to have access to "oc" in every S2I image.

**Comment by bparees** [comment]
>  the openshift/origin has entrypoint set to openshift, so if we are going to use it as base, we will have to change that entrypoint here. 

not really, we just have to ensure the final images change it,which they already do.  no one is supposed to run sti-base, so it really doesn't matter what its entrypoint is.

@mfojtik note that if we're doing this, there's no point in switching to the other centos stream per your other issue, so you might as well close it, or move that issue to origin so we can talk about switching the base centos image for the origin images.

**Comment by mfojtik** [comment]
@bparees right, for that I need to know why we use `centos:centos7` in origin instead of `centos:7` :-) But will transfer the issue to origin.

**Comment by rhcarvalho** [comment]
> why we use centos:centos7 in origin instead of centos:7

Those two tags point to the same image! :yum: 

https://hub.docker.com/_/centos/

**Comment by bparees** [comment]
> Those two tags point to the same image! :yum:

maybe today they do since centos was just rebuilt for the libc bug, but the intent going forward is that centos:7 will be updated more frequently.  At least that is what some quote @mfojtik provided indicated.

(and pointing to the same dockerfile doesn't mean they have to point to the same image, since one tag could be rebuilt more recently than another, thus picking up newer packages or even changes to the dockerfile itself)

**Comment by rhcarvalho** [comment]
Indeed they have different SHA256! https://github.com/docker-library/docs/blob/master/centos/tag-details.md

:scream_cat:  Docker Hub's UI fooled me, I always thought that the tags on the same line point to a single image.

**Comment by bparees** [comment]
> Docker Hub's UI fooled me, I always thought that the tags on the same line point to a single image.

yeah that is not a fantastic UI decision.....

**Comment by mfojtik** [comment]
@bparees @rhcarvalho I think the original issue was about changing FROM to origin-base, which is not what we are going to do AFAIK. If you have concerns or want to discuss using different bas image (I don't see the reason to do so, and I'm fine using 'centos7' tag as `latest` is not a version) please open separate issue.
