### ISSUE TITLE
[follow-up] Change the way we enable SCL collections

### ISSUE THREAD

**Issue by mfojtik** [openshift/sti-base#38]
Currently, we use `BASH_ENV=$HOME/.bashrc` where the `.bashrc` file does the SCL magic. I realized that this is not ideal at all:

* `$HOME/.bashrc` is writable for users and if user has that file in GIT repo, it will be overridden
* `.bashrc` name is unfortunate as it really is just enabling required SCL collection
* `.bashrc` is used in https://github.com/openshift/sti-python/blob/master/3.3/contrib/src/.bashrc#L5 to generate arbitrary UID for user which is not ideal because this will run for every shell session/sub-shell, including docker exec

What I propose here is:

* Move `/opt/openshift/src/.bashrc` to `/opt/openshift/etc/scl_enable` where this file will contain **only** the `scl enable` commands.
* Set `ENV BASH_ENV=/opt/openshift/etc/scl_enable`
* Create `/opt/openshift/etc/generate_container_user` which will do the arbitrary user generation. This file will be sourced by the STI run script

**Comment by mfojtik** [comment]
@bparees @soltysh @mnagy  @rhcarvalho PTAL

**Comment by bparees** [comment]
> Create /opt/openshift/etc/generate_container_user which will do the arbitrary user generation. This file will be sourced by the STI run script

may need to be run by assemble (and save-artifacts) too?  depending on what craziness they are doing...

otherwise this looks/sounds good.

**Comment by mfojtik** [comment]
This is no-go change for now as this will break the interactive bash sessions (where the only file that is read is `$HOME/.bashrc`... This will be fixed once we move our HOME from /opt/openshift/src to /opt/app-root. Then we can inject .bashrc there and it will not conflict.

**Comment by soltysh** [comment]
SGTM

**Comment by mfojtik** [comment]
taking my last comment back, i found a way how to trick it

**Comment by mnagy** [comment]
@mfojtik just one thing. Since you're moving the scl enable file, I'd propose moving it to /etc/profile.d/scl_source.sh so it get's picked up for login shells.

**Comment by mfojtik** [comment]
@mnagy login shell is covered by PROMPT_COMMAND

**Comment by mfojtik** [comment]
@mnagy is working on databases

**Comment by mfojtik** [comment]
@bparees ready for merge (and tested)

**Comment by bparees** [comment]
merged (though not successfully built yet :( )
