### ISSUE TITLE
Permission denied on /opt/app-root/src when running images on Boot2Docker vm

### ISSUE THREAD

**Issue by csrwng** [openshift/sti-base#81]
When running images based on sti-base in a Boot2Docker (or docker-machine) vm (Docker 1.10), the default user does not own all files under /opt/app-root/src. Usually there is a directory .pki/nssdb that the default user can't access. This causes all builds to fail because the assemble script can't fix up permissions:
```
bash-4.2$ ls -alR
.:
total 12
drwxr-xr-x 4 default root 4096 Mar  7 18:05 .
drwxr-xr-x 9 default root 4096 Mar  7 17:29 ..
drwxr----- 4 default root 4096 Mar  7 18:05 .pki

./.pki:
ls: cannot access ./.pki/nssdb: Permission denied
total 8
drwxr----- 4 default root 4096 Mar  7 18:05 .
drwxr-xr-x 4 default root 4096 Mar  7 18:05 ..
d????????? ? ?       ?       ?            ? nssdb
ls: cannot open directory ./.pki/nssdb: Permission denied
```

Running the same image on a Fedora OS with Docker, there is no such problem:
```
bash-4.2$ ls -alR
.:
total 0
drwxr-xr-x. 3 default root 17 Mar  7 18:05 .
drwxr-xr-x. 4 default root 26 Mar  7 17:29 ..
drwxr-----. 3 default root 18 Mar  7 18:05 .pki

./.pki:
total 0
drwxr-----. 3 default root 18 Mar  7 18:05 .
drwxr-xr-x. 3 default root 17 Mar  7 18:05 ..
drwxr-----. 2 default root  6 Mar  7 18:05 nssdb

./.pki/nssdb:
total 0
drwxr-----. 2 default root  6 Mar  7 18:05 .
drwxr-----. 3 default root 18 Mar  7 18:05 ..
```

It could be a storage driver issue, the Fedora install is using LVM, the Boot2Docker vm is using aufs:
```
$ docker info
Containers: 38
 Running: 7
 Paused: 0
 Stopped: 31
Images: 125
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 276
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.79 GiB
Name: openshift
ID: Y3LH:V5CP:VT5C:MFLI:PPU7:HE4A:SGZG:LFRY:RKWI:NML2:4XAT:DBAX
Debug mode (server): true
 File Descriptors: 63
 Goroutines: 83
 System Time: 2016-03-10T23:02:26.740319013Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

So the question is, is there a reason we keep that directory in /app/root/src ? Can it be deleted in this layer?

**Comment by csrwng** [comment]
@bparees

**Comment by bparees** [comment]
@csrwng we can fix the permissions in the base image:
https://github.com/openshift/sti-wildfly/commit/b24c9eaa64bdafdc4f704ef5bf8f894675265db7

**Comment by bparees** [comment]
err, in the builder image (it gets created by things installed after sti-base is built)

**Comment by bparees** [comment]
you've got the recreate env, i'll let you fix 'em :)

**Comment by bparees** [comment]
(I don't want to just remove the dir because i assume it has some value for nss wrapper, though perhaps not.  i haven't dug into exactly what that folder/file is for)

**Comment by csrwng** [comment]
cool, will do

**Comment by csrwng** [comment]
In the latest wildfly image 
```
openshift/wildfly-100-centos7               <none>              a8a4be32d8b6
```
I do see the same (wrong) permissions for that directory. However, builds don't fail... the error changing owner and permissions gets logged but the build continues.
I'll need to investigate a little bit more.

**Comment by csrwng** [comment]
Not sure that there's something to do in the Dockerfile itself to fix this. It may be more of a build process issue. I built the ruby image locally, as is, without changing anything on the Fedora machine. When I run it on the Boot2Docker vm, the permissions are correct.

**Comment by bparees** [comment]
As I recall graham only hit the issue on unsquashed images. All our images
are now built unsquashed by the push job. But you probably built it
squashed.  Try building it locally without squashing.

Ben Parees | OpenShift

**Comment by mfojtik** [comment]
@csrwng @bparees is there anything that left from fixing this on osx?

**Comment by csrwng** [comment]
@mfojtik thx for reminding me. It should be fixed.

**Comment by MrKarabil** [comment]
hi guys.. I have been struggling with this forbidden 403  Forbidden issue as well, and couldn't find a solution yet. I am trying to create image from this repository: https://karabil-admin@bitbucket.org/karabil-admin/masterportaladdonintegration.git
What I did is that I tried to create image from this repo by using nginx image of openshift. Build process seems to be working fine, but I got this 403 permission issue. Is there any practical way to fix it? (Please check screenshots attached to this message.

![Screenshot 2022-02-10 at 12-12-17 masterportalintegration01-7d875746ff-r4x5w · Details · Red Hat OpenShift Container Platform](https://user-images.githubusercontent.com/30593406/153396592-049f00af-b866-403d-947f-e9fb5dd2e5aa.png)
![Screenshot 2022-02-10 at 12-16-51 403 Forbidden](https://user-images.githubusercontent.com/30593406/153396612-20335be4-01b7-4544-bb39-cbfdd316651e.png)

![Screenshot 2022-02-10 at 12-12-46 Topology · Red Hat OpenShift Container Platform](https://user-images.githubusercontent.com/30593406/153396575-ec0fd5d6-d6f5-49d6-8899-9c49b0c9f390.png)

**Comment by bparees** [comment]
Based on the earlier discussion/resolution, you'd need to get the directory permissions fixed in the nginx image or perhaps update the assemble script (you can provide your own/override it) to set the appropriate permissions on the files during the assembly process.
